version: '3.8'
services:
  gameserver:
    container_name: gameserver
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    networks:
      - my-network
    depends_on:
      - game-db
    env_file:
      - ./.env
    volumes:
      - game-db-data:/var/lib/postgresql/data
    environment:
      - TYPEORM_HOST=game-db

  game-db:
    image: postgres:latest
    environment:
      POSTGRES_USER: ${GAME_DB_USER}
      POSTGRES_PASSWORD: ${GAME_DB_PASSWORD}
      POSTGRES_DB: ${GAME_DB_NAME}
    ports:
      - 5435:5432
    networks:
      - my-network
    volumes:
      - game-db-data:/var/lib/postgresql/data

  game-redis:
    image: redis:latest
    ports:
      - 6379:6379
    networks:
      - my-network
    volumes:
      - game-redis-data:/data

  nginx:
    image: nginx
    build:
      context: ./nginx
    restart: always
    ports:
      - 443:443
      - 80:80
      # - 3000:3000
    volumes:
      - cert_volume:/ect/letsencrypt

networks:
  my-network:
    name: my-network
    driver: bridge

volumes:
  game-db-data:
  game-redis-data:
  cert_volume:
    driver_opts:
      type: none
      o: 'bind'
      device: '${HOME}/certs'