version: '3.8'
services:
  gameserver:
    container_name: gameserver
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    networks:
      - my-network
    depends_on:
      - game-redis
    env_file:
      - ./.env
    environment:
      - TZ=Asia/Seoul

  game-redis:
    image: redis:latest
    ports:
      - 6379:6379
    networks:
      - my-network
    volumes:
      - game-redis-data:/data

  nginx:
    image: nginx
    build:
      context: ./nginx
    restart: always
    ports:
      - 443:443
      - 80:80
    volumes:
      - cert_volume:/etc/letsencrypt/

networks:
  my-network:
    name: my-network
    driver: bridge

volumes:
  game-redis-data:
  cert_volume:
    driver_opts:
      type: none
      o: 'bind'
      device: '${HOME}/certs'